server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

logging:
  level:
    root: warn
    cn.jinelei: debug

spring:
  datasource:
    url: jdbc:mysql://jinelei.cn:3306/aligenie
    username: root
    password: jin
    driver-class-name: com.mysql.jdbc.Driver

